### ISSUE TITLE
Executable model generation fails when a query contains an underscore in its name

### ISSUE THREAD

**Issue by mariofusco** [apache/incubator-kie-issues#1079]
When a query name contains an underscore the generation of the executable model fails with the following error

```
java.lang.NullPointerException: Cannot invoke "java.util.List.size()" because "queryParams" is null

	at org.drools.model.codegen.execmodel.generator.visitor.pattern.Query.buildPattern(Query.java:73)
	at org.drools.model.codegen.execmodel.generator.visitor.ModelGeneratorVisitor.visit(ModelGeneratorVisitor.java:132)
```

**Comment by mariofusco** [comment]
Fixed by https://github.com/apache/incubator-kie-drools/commit/fbbff6c00d1e45195c3d12da3ddd8ffde0d3a1fc
