### ISSUE TITLE
TypeError: Cannot assign to read-only property 'expression' in DMN Editor

### ISSUE THREAD

**Issue by kkumarDMS** [apache/incubator-kie-issues#1680]
An unexpected error occurred while using the DMN Editor in the IBM BAMOE Developer Tools extension for VS Code. The editor encountered a TypeError with the message:
Cannot assign to read-only property 'expression' of object '#<Object>'.

I was try to call Java method using BKM then coming this error.
Steps to Reproduce:
1. Open the DMN Editor in the IBM BAMOE Developer Tools extension (version 9.1.1).
2. Drag and drop a BKM and try call java method.

{
  "name": "TypeError",
  "message": "Cannot assign to read only property 'expression' of object '#<Object>'",
  "stack": "TypeError: Cannot assign to read only property 'expression' of object '#<Object>'
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:5440336
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:5970779
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:4734017
    at Object.produce (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:4734169)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:4734001
    at i (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:4592868)
    at n.setState (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:6184981)
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:5970728
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:5440304
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:5380018
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:5356256
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:5356305
    at https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:5354635
    at Rl (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:4389775)
    at t.unstable_runWithPriority (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:4548828)
    at $o (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:4330628)
    at Il (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:4389243)
    at Be (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:4401448)
    at Kt (https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/kisha/.vscode/extensions/ibm.bamoe-developer-tools-9.1.1/dist/webview/NewDmnEditorEnvelopeApp.js:2:4309411)"
}

Environment:
Extension Version: 9.1.1
VS Code Version: 1.95.3
Operating System: Windows 11

**Comment by yesamer** [comment]
Hi @kkumarDMS. This repository tracks issues for Apache KIE, not IBM BAMOE. Please refer to https://github.com/IBM/bamoe/issues.
