### ISSUE TITLE
Test cases in kogito repos GHA fail with "pull access denied for vectorized/redpanda"

### ISSUE THREAD

**Issue by tkobayas** [apache/incubator-kie-issues#1682]
As of 2024-Dec-11, kogito-runtimes, kogito-apps and kogito-examples GHA constantly fail.

https://github.com/apache/incubator-kie-drools/actions/runs/12251932205/job/34177520018?pr=6189
```
2024-12-10T08:28:01.0765524Z Caused by: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"pull access denied for vectorized/redpanda, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"}
2024-12-10T08:28:01.0767115Z
2024-12-10T08:28:01.0767995Z    at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
2024-12-10T08:28:01.0769917Z    at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
2024-12-10T08:28:01.0771173Z    ... 1 more
```

It seems that `vectorized/redpanda` was removed from docker hub. https://hub.docker.com/r/vectorized/redpanda

`redpandadata/redpanda` (https://hub.docker.com/r/redpandadata/redpanda) may be an alternative, but note that redpanda is under Business Source License 1.1 (https://github.com/redpanda-data/redpanda/blob/dev/licenses/bsl.md), which is Category X (https://www.apache.org/legal/resolved.html#category-x). Probably we will need to check with IPMC whether this usage (= just test infrastructure) is considered as "dependency" to be eventually removed before incubator graduation(https://issues.apache.org/jira/browse/LEGAL-469).

**Comment by porcelli** [comment]
@ricardozanini could you take a look at this issue?

**Comment by porcelli** [comment]
Based on past oracle drive usage, it's my understand that we need remove the dependency.

**Comment by tkobayas** [comment]
The above PRs are to fix test cases to make CI green.

---
The final goal of this GH issue would be, as discussed in https://lists.apache.org/thread/yhxxr2w77o39zv2fynsomn1wqo58k526 ,

A) Replace redpanda with another container which is under an acceptable license (e.g. apache/kafka)
or
B) Exclude the relevant test cases from the source distribution.

**Comment by tkobayas** [comment]
Per discussion in https://lists.apache.org/thread/yhxxr2w77o39zv2fynsomn1wqo58k526 and https://issues.apache.org/jira/browse/LEGAL-693 , it's fine to keep redpanda from license point of view.

Closing the issue.
