### ISSUE TITLE
TypeError when invoking Java method inside BKM

### ISSUE THREAD

**Issue by Kishan-kkumar** [apache/incubator-kie-issues#1734]
**Description:**
I encountered a TypeError while attempting to invoke a Java method inside a Business Knowledge Model (BKM) in the DMN editor. The error occurs consistently and prevents the proper execution of the intended functionality.

**Steps to Reproduce:**
1. Open the DMN editor at [sandbox.kie.org](https://sandbox.kie.org/).
2. Create or open a DMN model.
3. Add a Business Knowledge Model (BKM) to the canvas.
4. Attempt to invoke a Java method inside the BKM.
5. Observe the error.

**Expected Behavior:**
The Java method should be invoked successfully within the BKM, and the corresponding behavior should execute as expected.

**Actual Behavior:**
The following error occurs, halting the operation:

{
  "name": "TypeError",
  "message": "Cannot assign to read only property 'expression' of object '#<Object>'",
  "stack": "TypeError: Cannot assign to read only property 'expression' of object '#<Object>'
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4919143
    at getNewExpression (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4772205)
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4878098
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:5125756
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4761941
    at Object.produce (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4762093)
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4761925
    at i (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4620915)
    at n.setState (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:5543209)
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:5125703
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4878019
    at setExpression (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4772146)
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4919111
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4854570
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4829227
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4829276
    at https://sandbox.kie.org/new-dmn-editor-envelope.js:2:6080711
    at Pl (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4391159)
    at t.unstable_runWithPriority (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4548539)
    at Go (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4331794)
    at Il (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4390622)
    at Be (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4402863)
    at Qt (https://sandbox.kie.org/new-dmn-editor-envelope.js:2:4310559)"
}

**Environment:**
Product: https://sandbox.kie.org/#/
Product Version: 10.0.0
Browser: Chrome 131.0.6778
Operating System: Windows 11

**Video to Reproduce:**
![Bug](https://github.com/user-attachments/assets/4a1e52b7-dc6d-41ee-8d5b-72f2150aacd6)

**Comment by jomarko** [comment]
Thank you for reporting the issue, my guess from reading the logs is problem is somewhere in `JavaFunctionExpression`, but it is just a tip.

```
const onCellUpdates = useCallback(
    (cellUpdates: BeeTableCellUpdate<JAVA_ROWTYPE>[]) => {
      for (const u of cellUpdates) {
        const context: Normalized<DMN15__tContext> = functionExpression.expression!;

        const clazz = getClassContextEntry(context) ?? {
          "@_id": generateUuid(),
          expression: {
            __$$element: "literalExpression",
            "@_id": generateUuid(),
            text: { __$$text: "" },
          },
          variable: {
            "@_id": generateUuid(),
            "@_name": "class",
          },
        };
        const method = getVariableContextEntry(context) ?? {
          "@_id": generateUuid(),
          expression: {
            __$$element: "literalExpression",
            "@_id": generateUuid(),
            text: { __$$text: "" },
          },
          variable: {
            "@_id": generateUuid(),
            "@_name": "method signature",
          },
        };

        // Class
        if (u.rowIndex === 0) {
          setExpression((prev: Normalized<BoxedFunctionJava>) => {
            clazz.expression = {
              ...clazz.expression,
              __$$element: "literalExpression",
              text: {
                __$$text: u.value,
              },
            };

            // Do not inline this variable for type safety. See https://github.com/microsoft/TypeScript/issues/241
            const ret: Normalized<BoxedFunction> = {
              ...prev,
              expression: {
                __$$element: "context",
                ...context,
                contextEntry: [clazz, method],
              },
            };

            return ret;
          });
        }
        // Method
        else if (u.rowIndex === 1) {
          setExpression((prev: Normalized<BoxedFunctionJava>) => {
            method.expression = {
              ...method.expression,
              __$$element: "literalExpression",
              "@_id": method.expression["@_id"] ?? generateUuid(),
              text: {
                __$$text: u.value,
              },
            };

            // Do not inline this variable for type safety. See https://github.com/microsoft/TypeScript/issues/241
            const ret: Normalized<BoxedFunction> = {
              ...prev,
              expression: {
                __$$element: "context",
                ...context,
                contextEntry: [clazz, method],
              },
            };
            return ret;
          });
        }
      }
    },
    [functionExpression.expression, getClassContextEntry, getVariableContextEntry, setExpression]
  );
  ```

**Comment by Kusuma04-dev** [comment]
Closed by https://github.com/apache/incubator-kie-tools/pull/2831
