### ISSUE TITLE
PythonFlowIT is failing in the CI - GHA PR check

### ISSUE THREAD

**Issue by baldimir** [apache/incubator-kie-issues#788]
The test is failing like this in GHA PR check: 
2023-12-21T10:28:55.9424632Z Caused by: java.lang.ClassNotFoundException: jep.PyMethod
2023-12-21T10:28:55.9425868Z 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
2023-12-21T10:28:55.9427428Z 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
2023-12-21T10:28:55.9428736Z 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
2023-12-21T10:28:55.9429986Z 	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:115)
2023-12-21T10:28:55.9431372Z 	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:65)
2023-12-21T10:28:55.9432317Z 	... 67 more
2023-12-21T10:28:55.9432555Z 
2023-12-21T10:28:55.9434018Z [ERROR] Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 58.94 s <<< FAILURE! -- in org.kie.kogito.quarkus.workflows.PythonFlowIT
2023-12-21T10:28:55.9436077Z [ERROR] org.kie.kogito.quarkus.workflows.PythonFlowIT.testPythonService -- Time elapsed: 8.267 s <<< FAILURE!
2023-12-21T10:28:55.9437299Z java.lang.AssertionError: 
2023-12-21T10:28:55.9437802Z 1 expectation failed.
2023-12-21T10:28:55.9438294Z Expected status code <201> but was <500>.

**Comment by fjtirado** [comment]
@baldimir Is this failing in any environment or just in GHA? Im assuming where are talking about main branch.
